services:
  backend:
    build:
      dockerfile: docker-maven/Dockerfile
      context: backend
    ports:
      - "8888:8888"
    depends_on:
      - database

  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-infowijs}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-infowijs-secret}
      - POSTGRES_DB=${POSTGRES_DB:-infowijs}
      - POSTGRES_INITDB_ARGS=--auth=md5
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres: