services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - "8887:80"
    depends_on:
      - backend


  backend:
    build:
      dockerfile: docker-maven/Dockerfile
      context: backend
    ports:
      - "8888:8888"
    depends_on:
      - database

  database:
    build: 
      dockerfile: database/Dockerfile
      context: backend
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-infowijs}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-infowijs-secret}
      - POSTGRES_DB=${POSTGRES_DB:-infowijs}
      - POSTGRES_INITDB_ARGS=--auth=md5
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: